"""Added recurring transactions to Transaction model

Revision ID: 8a56f9522b3d
Revises: 0845410aadcb
Create Date: 2024-08-26 18:18:27.861104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a56f9522b3d'
down_revision = '0845410aadcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('recurring_sequence_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recurring_parent_id', 'transactions', ['recurring_parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('recurring_sequence_id')
        batch_op.drop_column('recurring_parent_id')

    # ### end Alembic commands ###
