"""Add OAuth fields to User model

Revision ID: fc3d6cbc3258
Revises: eb99d0d38f58
Create Date: 2025-04-08 17:20:58.754833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc3d6cbc3258'
down_revision = 'eb99d0d38f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('auth_provider_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint("uq_auth_provider_id", ['auth_provider_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('auth_provider_id')
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
